# This is a basic workflow to help you get started with Actions

name: Weekly Cron Job

on:
  schedule:
    - cron: "0 18 * * 0"  # Runs every Sunday at 6:00 PM ET (22:00 UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          API_KEY: ${{secrets.API_KEY}}
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: python main.py


